### ISSUE TITLE
Specify service name when importing artifact from OpenAPI2/3 contract

### ISSUE THREAD

**Issue by f-lopes** [microcks/microcks-testcontainers-java#113]
Is it possible (or at least will be in the future) to specify the service name when importing an artifact via the Java API?

https://github.com/microcks/microcks-testcontainers-java/blob/main/src/main/java/io/github/microcks/testcontainers/MicrocksContainer.java#L265

It would be especially useful when a contract.yaml uses a title with special characters (spaces, accents, etc.).

This way, the `getRestMockEndpoint()` method (https://github.com/microcks/microcks-testcontainers-java/blob/main/src/main/java/io/github/microcks/testcontainers/MicrocksContainer.java#L237) would return a properly formatted URL.

Thanks.

**Comment by lbroudoux** [comment]
Hey @f-lopes!

Special characters in API name or version are expected to be HTTP-encoded (at least, they are on Microcks core). Can you provide some examples that are not working on your side? Maybe we're not reproducing the same encoding on the library that what we're doing on server side...

**Comment by f-lopes** [comment]
Hey @lbroudoux!

Thanks for your response.

I can't share the exact example that is not working on my side. However, when importing an artifact (OpenAPI v2) with a title containing both spaces and accents (for example, `API permettant de gérer les pâtisseries`), the `microcksContainer.getRestMockEndpoint("API permettant de gérer les pâtisseries", "1.0.0")` returns a URL containing the same title (meaning it is not encoded at all).

Isn't that endpoint URL expected to be encoded?

Thanks.

**Comment by lbroudoux** [comment]
I'm afraid you're right and we screwed the encoding part. Let's fix this! I'm going to create another issue to track this bug.

**Comment by lbroudoux** [comment]
#116 has been crated to track this one.
